### ISSUE TITLE
GWT-specific i18n formats not supported

### ISSUE THREAD

**Issue by crevete** [lightoze/gwt-i18n-server#16]
The GWT-specific i18n format is currently not supported yet (See http://www.gwtproject.org/doc/latest/DevGuideI18nMessages.html#GwtFormats)

Here is a simple example :

In the properties file :

```
hello = Hello, {startBold,<b>}{0}{endBold,</b>}
```

When rendering this message on the server side, an exception will be thrown :

```
java.lang.IllegalArgumentException: can't parse argument number: startBold
    at java.text.MessageFormat.makeFormat(MessageFormat.java:1420)
    at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
    at java.text.MessageFormat.<init>(MessageFormat.java:381)
    at net.lightoze.gwt.i18n.server.MessagesProxy.invoke(MessagesProxy.java:107)
```

**Comment by lightoze** [comment]
Partially fixed this in 0.24 - now you can use `{startBold,<b>}{0}{endBold,</b>}`. Other GWT-specific formats are still not supported.
